# Generated by Django 3.1 on 2020-08-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countViewsDownload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='qwerty',
            new_name='FJournal',
        ),
    ]
