# Generated by Django 3.1 on 2020-08-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countViewsDownload', '0003_auto_20200806_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hit',
            name='ip_address',
        ),
    ]
