# Generated by Django 3.1 on 2020-08-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countViewsDownload', '0004_remove_hit_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
